comment out jacoco to avoid class instrumentation failures
looks like jacoco is an instrumentation library that synthea uses to
check code coverage of tests. causes weird problems like:
java.lang.instrument.IllegalClassFormatException: Error while instrumenting sun/util/resources/cldr/provider/CLDRLocaleDataMetaInfo.